### ISSUE TITLE
Implement `redistribute`

### ISSUE THREAD

**Issue by Andre-Medina** [Andre-Medina/Electoralyze#32]
## Current situation

Meta task for the `redistribute` function for redistributing data between regions.

## Expected solution

- [x] From SA1-> SA2 by geographical area  #11
- [x] From PP_ID -> SA1 using custom mapping #11 
- [ ] From LGA 2016 -> LGA 2022 through SA1 by population #18
- [ ] possibility to map with centroids #19
