### ISSUE TITLE
Ready for contribution

### ISSUE THREAD

**Issue by Andre-Medina** [Andre-Medina/Electoralyze#5]
## Current situation

Need to get the repo ready for other to contribute

The repo needs several improvements to help streamline the experience. 

## Expected solution

- [x] Add GH actions 
  - [x] PR name
  - [x] Branch name
  - [x] Issue name: Idk if this is working. #13
  - [x] unit tests
  - [x] merge queue + integration test. #10 
  - [x] dependabot
- [x] Templates
  - [x] bug
  - [x] feature template.
  - [x] PR template
- [x] Update Readme
  - [x] How to contribute
  - [x] Update install instructions
  - [x] What each sub package does
